# Generated by Django 2.1 on 2021-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kids',
            name='score',
            field=models.IntegerField(),
        ),
    ]
